apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: fireplace
  name: pvc-fireplace
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-client
  resources:
    requests:
      storage: 10Gi
