apiVersion: v1
kind: Service
metadata:
  labels:
    app: fireplace-app-service
  name: fireplace-app-service
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 3000
  selector:
    app: fireplace-backend
